"""
Data Message (DM)

Implements the primary telemetry message used to transmit sensor data
from a Local Controller to the Main Controller.
"""

from ramp_messages import RampMessage


class DataMessage(RampMessage):
    """
    Data Message (DM).

    Encapsulates contextual metadata and structured sensor payloads
    generated by a Local Controller.
    """

    def __init__(
        self,
        lc_id: str,
        location: list[float],
        system_type: str,
        payload: list[dict],
        specs: dict | None = None,
    ):
        """
        Initialize a Data Message.

        Parameters
        ----------
        lc_id : str
            Identifier of the Local Controller.
        location : list of float
            Geographic coordinates [latitude, longitude].
        system_type : str
            System category (e.g., RS for rolling stock, TS for trackside).
        payload : list of dict
            Sensor data payload.
        specs : dict, optional
            Deployment-specific metadata.
        """
        super().__init__(lc_id)
        self.location = location
        self.system_type = system_type
        self.payload_data = payload
        self.specs = specs

    @property
    def msg_type(self) -> str:
        """Return the message type identifier."""
        return "DM"

    @property
    def topic(self) -> str:
        """Return the data publication topic."""
        return f"/lc/{self.lc_id}/data/"

    def payload(self) -> dict:
        """
        Build the data message payload.

        Returns
        -------
        dict
            Data message payload.
        """
        data = {
            "location": self.location,
            "type": self.system_type,
            "timestamp": self.timestamp,
            "payload": self.payload_data,
        }
        if self.specs:
            data["specs"] = self.specs
        return data
